version: "3.3"

services: 
    web:
        build: ./backend
        command: >
            bash -c "python manage.py runserver 0.0.0.0:8080"
        volumes: 
            - ./backend:/app
        ports: 
            - "8080:8080"
    fe:
        build: ./frontend
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - "/app/node_modules"
            - ./frontend:/app
        ports:
            - 3000:3000