# Generated by Django 3.2.4 on 2021-06-04 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('PMID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=512)),
                ('Abstract', models.TextField(max_length=5000, null=True)),
                ('Authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None)),
                ('Keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None)),
            ],
        ),
    ]
