# Generated by Django 3.2.4 on 2021-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Tokenized',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
