# Generated by Django 3.2.4 on 2021-06-08 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_tokenized'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanArticle',
            fields=[
                ('PMID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=512)),
                ('Abstract', models.TextField(max_length=5000, null=True)),
                ('Authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None)),
                ('Keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None)),
                ('Tokenized', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), null=True, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='Tokenized',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), null=True, size=None),
        ),
    ]
