# Generated by Django 3.2.4 on 2021-06-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210608_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanarticle',
            name='TopicClass',
            field=models.IntegerField(default=0),
        ),
    ]
